name: Pre-commit

on:
  pull_request:
  push:
    branches: [main, master, backend]

permissions:
  contents: write
  actions: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR/source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        id: pre_commit
        run: |
          set -e
          pre-commit install
          if pre-commit run --all-files; then
            echo "pre_commit_passed=true" >> $GITHUB_OUTPUT
          else
            echo "pre_commit_passed=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Check for changes (excluding workflows)
        id: check_changes
        run: |
          # Stage any auto-fixes
          git add -A
          # Avoid committing workflow changes
          git reset -- .github/workflows/ || true
          if [ -n "$(git diff --cached --name-only)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected (excluding workflows)"
            echo "Changed files:"
            git diff --cached --name-only
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes to commit"
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "style: auto-fix pre-commit issues [skip ci]"
          git push origin HEAD:${{ github.head_ref || github.ref_name }}

      - name: Report unfixable issues
        if: steps.pre_commit.outputs.pre_commit_passed == 'false' && steps.check_changes.outputs.has_changes == 'false'
        run: |
          echo "⚠️ Pre-commit found issues that couldn't be auto-fixed!"
          echo "Please check the pre-commit output above and fix manually."
          echo "Common issues:"
          echo "- Syntax errors in Python files"
          echo "- Complex linting violations"
          echo "- Files that need manual review"
          exit 1
